groceries = ["Bread", "Eggs", "Rice", "Butter", "Vegetables"]
print("List:", groceries)
print("First element:", groceries[0])
print("Last element:", groceries[-1])
print("No. of items:", len(groceries))
print("Slicing:", groceries[1:4])
groceries.append("Oatmeal")
print("Updated groceries after adding:", groceries)
groceries.remove("Rice")
print("Updated groceries after removing:", groceries)
groceries.reverse()
print("After reversing:", groceries)
groceries.sort()
print("After sorting:", groceries)
groceries.pop(1)
print("After popping:", groceries)
groceries.clear()
print("After clearing:", groceries)
